2024.2.0 update
AnacondaRecipes/fastparquet-feedstock pull request #10
Opened 2024-05-07 15:51 UTC by JamesRobertsonGames

[fastparquet-feedstock](https://github.com/AnacondaRecipes/fastparquet-feedstock) 2024.2.0

**Destination channel:** defaults

### Links

- [PKG-4507](https://anaconda.atlassian.net/browse/PKG-4507) 
- [Upstream repository](https://github.com/dask/fastparquet)
- [Upstream changelog/diff](https://github.com/dask/fastparquet/releases/tag/2024.2.0)

### Explanation of changes:
- update version, enhance dependencies, update pinnings, and increase testing

2024-05-07 15:52 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_41k5t0b8ck/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:34: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:25: cython_must_be_in_host: Cython should be in the host section
===== Final Report: =====
1 Error and 1 Warning were found

</details>

2024-05-08 13:11 UTC, JeanChristopheMorinPerso requested changes

2024-05-08 13:11 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - packaging
I don't think this is needed.

2024-05-08 13:11 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    -  mv ./fastparquet ./fastparquet-src
```suggestion
```
Not needed.

2024-05-08 13:11 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - fastparquet-src
```suggestion
    - fastparquet/test
```

2024-05-08 13:11 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
>    commands:
```suggestion
  requires:
    - pip
    - pytest
  commands:
    - pytest -v fastparquet/test
```

2024-05-08 13:11 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
>      - pytest-runner
```suggestion
```

2024-05-09 08:20 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - fastparquet/test
The _Source Distribution_ on `PyPI` doesn't contain the `test` folder, see https://pypi.org/project/fastparquet/#files

2024-05-09 08:21 UTC, JamesRobertsonGames commented
@JeanChristopheMorinPerso Applied your changes just to make sure my testing was correct
- Tests are excluded from the setup.py and are not here https://github.com/dask/fastparquet/blob/bb00f37f211d979cc2779dc2adfd6313b9c069d4/setup.py#L85
- Once this is fixed, there will be an issue with importing the cython dependencies unless I move the source code to another file, I believe due to a filename clash, I can't personally find another way to repair this

2024-05-09 09:24 UTC, skupr-anaconda approved these changes

2024-05-09 13:29 UTC, JeanChristopheMorinPerso approved these changes
Looks good to me, thanks @JamesRobertsonGames. My suggestion is cosmetic only and doesn't have to be applied before merging.

2024-05-09 13:29 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
```suggestion
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
```

2024-05-09 13:43 UTC, merged